# This workflow will install Python dependencies, run tests and other codechecks on SPSDK project

name: Python Continous Integration

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  codecheck-ubuntu:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        #os: [ubuntu-latest,windows-latest,macos-latest]
        os: [ubuntu-latest]
        #python-version: ['3.7','3.10']
        python-version: ['3.10']

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set-up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ matrix.python-version }}
        architecture: 'x64'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-develop.txt

    - name: Install SPSDK
      run: |
        # This is required for dependencies check
        python setup.py install

    - name: Run Codecheck - Master
      if: github.event_name == 'push'
      run: |
        python codecheck.py -s --output reports_codecheck --check BLACK --check ISORT
        #python codecheck.py -s --output reports_codecheck --info-check gitcov --info-check copyright

    - name: Run Codecheck - Pull Request
      if: github.event_name == 'pull_request'
      run: |
        python codecheck.py -s --output reports_codecheck

    - name: Archive Results
      uses: actions/upload-artifact@v3
      with:
        name: Results-${{ matrix.python-version }}-${{ matrix.os }}
        path: reports_codecheck
      #if: always() && job.status == 'failure'

